[build]
  command = "pnpm install --no-frozen-lockfile && pnpm run build"
  publish = "dist"

[build.environment]
  NODE_ENV = "production"
  NPM_FLAGS = "--no-frozen-lockfile"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200